package edu.umsl.sets;

import java.util.Objects;

public class Car {

	String name;
	String type;
	int numberOfDoors;

	public Car(String name, String type, int numberOfDoors) {
		this.name = name;
		this.type = type;
		this.numberOfDoors = numberOfDoors;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getNumberOfDoors() {
		return numberOfDoors;
	}

	public void setNumberOfDoors(int numberOfDoors) {
		this.numberOfDoors = numberOfDoors;
	}

	@Override //random value computed by the machine to provide unique result
	public int hashCode() {
		//autogenerated code 
		/*final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + numberOfDoors;
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		return result;*/
		//or just use this
		return Objects.hash(name, type, numberOfDoors);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Car other = (Car) obj;
		
		//autogenerated code
		/*if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (numberOfDoors != other.numberOfDoors)
			return false;
		if (type == null) {
			if (other.type != null)
				return false;
		} else if (!type.equals(other.type))
			return false;
		return true; */
		
		//or just use this
		return numberOfDoors == other.numberOfDoors && Objects.equals(name, other.name) 
				&& Objects.equals(type, other.type);
	}
	
	

}
